### ISSUE TITLE
[BUG] Multiple deploy attempts for a successful deployment

### ISSUE THREAD

**Issue by andreamontanari** [awslabs/autonomous-driving-data-framework#14]
**Describe the bug**
By following the blog post on AWS, the deploy command "seedfarmer apply ./manifests/demo/deployment.yaml" should deploy all the needed modules to your AWS account.

In my situation, from a macbook Pro with cdk version 2.20 and seed-farmer~=0.1.1, I had to run the deploy command multiple times because at each execution I was facing a similar error.

```
...
Traceback (most recent call last):
  File "/Users/andmoa/Documents/workspace/aws/artifacts/autonomous-driving-data-framework/.venv/bin/seedfarmer", line 8, in <module>
    sys.exit(main())
  File "/Users/andmoa/Documents/workspace/aws/artifacts/autonomous-driving-data-framework/.venv/lib/python3.9/site-packages/seedfarmer/__main__.py", line 518, in main
    cli()
  File "/Users/andmoa/Documents/workspace/aws/artifacts/autonomous-driving-data-framework/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/andmoa/Documents/workspace/aws/artifacts/autonomous-driving-data-framework/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/andmoa/Documents/workspace/aws/artifacts/autonomous-driving-data-framework/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/andmoa/Documents/workspace/aws/artifacts/autonomous-driving-data-framework/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/andmoa/Documents/workspace/aws/artifacts/autonomous-driving-data-framework/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/andmoa/Documents/workspace/aws/artifacts/autonomous-driving-data-framework/.venv/lib/python3.9/site-packages/seedfarmer/__main__.py", line 70, in apply
    commands.apply(spec, dry_run, show_manifest)
  File "/Users/andmoa/Documents/workspace/aws/artifacts/autonomous-driving-data-framework/.venv/lib/python3.9/site-packages/seedfarmer/commands/_deployment_commands.py", line 454, in apply
    deploy_deployment(
  File "/Users/andmoa/Documents/workspace/aws/artifacts/autonomous-driving-data-framework/.venv/lib/python3.9/site-packages/seedfarmer/commands/_deployment_commands.py", line 383, in deploy_deployment
    _deploy_deployment_is_not_dry_run(
  File "/Users/andmoa/Documents/workspace/aws/artifacts/autonomous-driving-data-framework/.venv/lib/python3.9/site-packages/seedfarmer/commands/_deployment_commands.py", line 192, in _deploy_deployment_is_not_dry_run
    _ = list(workers.map(_exec_deploy, params))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/andmoa/Documents/workspace/aws/artifacts/autonomous-driving-data-framework/.venv/lib/python3.9/site-packages/seedfarmer/commands/_deployment_commands.py", line 177, in _exec_deploy
    return _execute_deploy(
  File "/Users/andmoa/Documents/workspace/aws/artifacts/autonomous-driving-data-framework/.venv/lib/python3.9/site-packages/seedfarmer/commands/_deployment_commands.py", line 111, in _execute_deploy
    return commands.deploy_module(
  File "/Users/andmoa/Documents/workspace/aws/artifacts/autonomous-driving-data-framework/.venv/lib/python3.9/site-packages/seedfarmer/commands/_module_commands.py", line 106, in deploy_module
    return _execute_module_commands(
  File "/Users/andmoa/Documents/workspace/aws/artifacts/autonomous-driving-data-framework/.venv/lib/python3.9/site-packages/seedfarmer/commands/_module_commands.py", line 212, in _execute_module_commands
    _execute_module_commands(
  File "/Users/andmoa/Documents/workspace/aws/artifacts/autonomous-driving-data-framework/.venv/lib/python3.9/site-packages/aws_codeseeder/codeseeder.py", line 348, in wrapper
    build_info = _remote.run(
  File "/Users/andmoa/Documents/workspace/aws/artifacts/autonomous-driving-data-framework/.venv/lib/python3.9/site-packages/aws_codeseeder/_remote.py", line 102, in run
    build_info = _execute_codebuild(
  File "/Users/andmoa/Documents/workspace/aws/artifacts/autonomous-driving-data-framework/.venv/lib/python3.9/site-packages/aws_codeseeder/_remote.py", line 82, in _execute_codebuild
    return _wait_execution(
  File "/Users/andmoa/Documents/workspace/aws/artifacts/autonomous-driving-data-framework/.venv/lib/python3.9/site-packages/aws_codeseeder/_remote.py", line 43, in _wait_execution
    for status in codebuild.wait(build_id=build_id):
  File "/Users/andmoa/Documents/workspace/aws/artifacts/autonomous-driving-data-framework/.venv/lib/python3.9/site-packages/aws_codeseeder/services/codebuild.py", line 240, in wait
    build = fetch_build_info(build_id=build_id)
  File "/Users/andmoa/Documents/workspace/aws/artifacts/autonomous-driving-data-framework/.venv/lib/python3.9/site-packages/aws_codeseeder/services/codebuild.py", line 189, in fetch_build_info
    phases=[
  File "/Users/andmoa/Documents/workspace/aws/artifacts/autonomous-driving-data-framework/.venv/lib/python3.9/site-packages/aws_codeseeder/services/codebuild.py", line 192, in <listcomp>
    status=None if "phaseStatus" not in p else BuildPhaseStatus(value=p["phaseStatus"]),
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/enum.py", line 360, in __call__
    return cls.__new__(cls, value)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/enum.py", line 677, in __new__
    raise ve_exc
ValueError: 'CLIENT_ERROR' is not a valid BuildPhaseStatus
```

In addition to the above error, in the main build project, in the build history there are very short builds with FAILED status.
By checking the logs in the Phase details tab, the following message appears:

```
ACCESS_DENIED: Service role arn:aws:iam::086314134900:role/addf-demo-integration-opensearch-proxy-c4fd8732 does not allow AWS CodeBuild to create Amazon CloudWatch Logs log streams for build arn:aws:codebuild:eu-west-1:086314134900:build/codeseeder-addf:115d0983-6fbe-4b28-a9fd-c30189935653. Error message: User: arn:aws:sts::086314134900:assumed-role/addf-demo-integration-opensearch-proxy-c4fd8732/AWSCodeBuild-115d0983-6fbe-4b28-a9fd-c30189935653 is not authorized to perform: logs:CreateLogStream on resource: arn:aws:logs:eu-west-1:086314134900:log-group:/aws/codebuild/codeseeder-addf:log-stream:codeseeder-vtqrmder/115d0983-6fbe-4b28-a9fd-c30189935653 because no identity-based policy allows the logs:CreateLogStream action
```

**To Reproduce**
 - follow blog steps
 - run deploy command
 - wait for output

**Expected behavior**
The deploy command should successfully complete for all modules, without the user needing to run the same command multiple times.

**Screenshots**

![Screenshot 2022-07-12 at 15 01 55](https://user-images.githubusercontent.com/5418162/178496299-b43b5d60-8021-45b2-bcd4-c5abeaa4bd70.png)

**Additional context**

**Comment by dgraeber** [comment]
Thanks for this issue report..we will investigate

**Comment by chamcca** [comment]
i'm able to reproduce, but not consistently. this appears to be an eventual consistency issue with IAM in the seed-farmer library. 

this Issue is being addressed here: https://github.com/awslabs/seed-farmer/issues/43
