### ISSUE TITLE
[BUG] Investigate Multi-Instance Deployment Issues (same account, different regions)

### ISSUE THREAD

**Issue by chamcca** [awslabs/autonomous-driving-data-framework#32]
By definition, the deployment of multiple ADDF instances in a single AWS account in the same region or same account different regions should work. 

Same account - Different region deployment issues:

1. addf-example-dev-core-eks-masterrole already exists (roles are global)

```bash
Custom::AWSCDKOpenIdConnectProviderCustomResourceProvider/Role (CustomAWSCDKOpenIdConnectProviderCustomResourceProviderRole517FED65) 
addf-example-dev-core-eks | 11/82 | 9:54:08 AM | DELETE_COMPLETE      | AWS::EFS::FileSystem                  | EFSFilesystem (EFSFilesystem073A610A) 

addf-example-dev-core-eks | 12/82 | 9:54:09 AM | ROLLBACK_COMPLETE    | AWS::CloudFormation::Stack            | addf-example-dev-core-eks 

Failed resources:

addf-example-dev-core-eks | 9:53:27 AM | CREATE_FAILED        | AWS::IAM::Role                        | ClusterAdminRole (ClusterAdminRole047D4FCA) addf-example-dev-core-eks-masterrole already exists

 ❌  addf-example-dev-core-eks failed: Error: The stack named addf-example-dev-core-eks failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE

    at waitForStackDeploy (/usr/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:311:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at prepareAndExecuteChangeSet (/usr/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:376:26)
    at CdkToolkit.deploy (/usr/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:209:24)
    at initCommandLine (/usr/lib/node_modules/aws-cdk/lib/cli.ts:342:12)
```

**Comment by chamcca** [comment]
existing modules should be reviewed to ensure the Roles they create are unique for a given deployment. these could be named using hashes or include region identifier. 

seed-farmer v2.0 will address this, but in the meantime ADDF modules could be patched

**Comment by dgraeber** [comment]
For the stack trace above, the use of the 'masterrole' suffix on the role is causing the issue (in this case).  Searching for `masterrole` and where to be remediated by adding the hash suffix:

- modules/core/eks/stack.py
- modules/core/eks/modulestack.yaml
- modules/core/eks/deployspec.yaml
- modules/core/aws-batch/modulestack.yaml

The above files for `eks` need to make sure the role names are correlated to one another.  The instance in `aws-batch` seems like a single instance

**Comment by dgraeber** [comment]
The issue in `core/aws-batch` has been addressed in https://github.com/awslabs/autonomous-driving-data-framework/pull/35
