### ISSUE TITLE
[BUG] EKS Module Deployment Issues

### ISSUE THREAD

**Issue by malachi-constant** [awslabs/autonomous-driving-data-framework#574]
**Describe the bug**
Deploying the EKS Module yields an error

```bash
[Container] 2024/08/27 21:52:08.217370 Running command cdk deploy --require-approval never --progress events --app "python app.py" --outputs-file ./cdk-exports.json
--
626 | Traceback (most recent call last):
627 | File "/codebuild/output/src967942608/src/bundle/module/app.py", line 57, in <module>
628 | stack = Eks(
629 | ^^^^
630 | File "/root/.venv/lib/python3.11/site-packages/jsii/_runtime.py", line 118, in __call__
631 | inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
632 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
633 | File "/codebuild/output/src967942608/src/bundle/module/stack.py", line 215, in __init__
634 | self._create_managed_node_group(eks_cluster, eks_version, ng, node_capacity_type, vpc_cni_chart)
635 | File "/codebuild/output/src967942608/src/bundle/module/stack.py", line 452, in _create_managed_node_group
636 | taints=[
637 | ^
638 | File "/codebuild/output/src967942608/src/bundle/module/stack.py", line 456, in <listcomp>
639 | effect=eks.TaintEffect(taint.get("effect").upper()),
640 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
641 | File "/root/.pyenv/versions/3.11.9/lib/python3.11/enum.py", line 714, in __call__
642 | return cls.__new__(cls, value)
643 | ^^^^^^^^^^^^^^^^^^^^^^^
644 | File "/root/.pyenv/versions/3.11.9/lib/python3.11/enum.py", line 1137, in __new__
645 | raise ve_exc
646 | ValueError: 'NOSCHEDULE' is not a valid TaintEffect
```

I believe this value should be `NO_SCHEDULE` with an underscore from the documentation. Please investigate.

**To Reproduce**
Deploy the latest version of the `ml-training-on-eks` manifest.

**Comment by srinivasreddych** [comment]
I will be looking into it today
