### ISSUE TITLE
[BUG] YOLOP Lane Detection Image Scaling Issue

### ISSUE THREAD

**Issue by a13zen** [awslabs/autonomous-driving-data-framework#69]
**Describe the bug**
When running the out of box VSI-DEMO MWAA Dag on the public Rosbag files from the blog post (s3://aws-autonomous-driving-datasets/test-vehicle-01/072021/small1__2020-11-19-16-21-22_4.bag) the SageMaker Processing job for Lane Detection fails with errors around img size (scaling). It seems to always be off by specific factor 0.8 (600->480), (1200->960)

**To Reproduce**
1. Deploy the ros-image-demo manifest
2. Copy the public bag file above into your account into the addf raw bucket (you need to copy it twice since the batch job needs min of 2 files (another bug)
3. Run the VSI sample data DAG with config similar to:

```json
{
    "drives_to_process": {
        "test-vehicle-01": {
            "bucket": "<addf-raw-bucket>",
            "prefix": "test-vehicle-01/072021/"
        },
        "test-vehicle-02": {
            "bucket": "<addf-raw-bucket>",
            "prefix": "test-vehicle-02/072021/"
        }
    }
}
```
4. Check pipeline. Last step fails, sagemaker processing job with logs below

**Expected behavior**

**Screenshots**

```bash
/opt/conda/lib/python3.8/site-packages/torchvision/io/image.py:11: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")

Using torch 1.10.2+cpu CPU
['/YOLOP/tools', '/opt/conda/lib/python38.zip', '/opt/conda/lib/python3.8', '/opt/conda/lib/python3.8/lib-dynload', '/opt/conda/lib/python3.8/site-packages', '/YOLOP']
=> creating runs/BddDataset/_2022-11-18-15-44
#015  0%|          | 0/202 [00:00<?, ?it/s]/opt/conda/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2156.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py:3631: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
#015  0%|          | 0/202 [00:00<?, ?it/s]
image 1/202 /opt/ml/processing/input/image/frame_0005407_1605824495_875984259.png: 
Traceback (most recent call last):
  File "tools/detect_lanes.py", line 226, in <module>
    detect(cfg, opt)
  File "tools/detect_lanes.py", line 147, in detect
    img_det = show_seg_result(img_det, (da_seg_mask, ll_seg_mask), _, _, is_demo=True)
  File "/YOLOP/lib/utils/plot.py", line 57, in show_seg_result
    img[color_mask != 0] = img[color_mask != 0] * 0.5 + color_seg[color_mask != 0] * 0.5
    IndexError: boolean index did not match indexed array along dimension 0; dimension is 1200 but corresponding boolean dimension is 960
```

**Comment by dgraeber** [comment]
Please confirm that this PR corrected the issue:
https://github.com/awslabs/autonomous-driving-data-framework/pull/54

@a13zen @kevinsoucy

**Comment by kevinsoucy** [comment]
confirmed @dgraeber

**Comment by JunjieTang-D1** [comment]
can we close this bug? @dgraeber
